/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hmi_tts_sapi5_SAPI5TTSGenerator_BookMarker */

#ifndef _Included_hmi_tts_sapi5_SAPI5TTSGenerator_BookMarker
#define _Included_hmi_tts_sapi5_SAPI5TTSGenerator_BookMarker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
