/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hmi_tts_sapi5_SAPI5TTSGenerator */

#ifndef _Included_hmi_tts_sapi5_SAPI5TTSGenerator
#define _Included_hmi_tts_sapi5_SAPI5TTSGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hmi_tts_sapi5_SAPI5TTSGenerator
 * Method:    SAPISpeak
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_sapi5_SAPI5TTSGenerator_SAPISpeak
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hmi_tts_sapi5_SAPI5TTSGenerator
 * Method:    SAPIDummySpeak
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_sapi5_SAPI5TTSGenerator_SAPIDummySpeak
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hmi_tts_sapi5_SAPI5TTSGenerator
 * Method:    SAPIInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_sapi5_SAPI5TTSGenerator_SAPIInit
  (JNIEnv *, jobject);

/*
 * Class:     hmi_tts_sapi5_SAPI5TTSGenerator
 * Method:    SAPISetSpeaker
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_sapi5_SAPI5TTSGenerator_SAPISetSpeaker
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hmi_tts_sapi5_SAPI5TTSGenerator
 * Method:    SAPIGetVoices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hmi_tts_sapi5_SAPI5TTSGenerator_SAPIGetVoices
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_hmi_tts_sapi5_SAPI5TTSGenerator_SAPISpeakToFile (JNIEnv *env, jobject obj, jstring _text, jstring _filename);

JNIEXPORT jint JNICALL Java_hmi_tts_sapi5_SAPI5TTSGenerator_SAPICleanup(JNIEnv *env, jobject obj);
#ifdef __cplusplus
}
#endif
#endif
