/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hmi_tts_fluency8_Fluency8TTSGenerator */

#ifndef _Included_hmi_tts_fluency8_Fluency8TTSGenerator
#define _Included_hmi_tts_fluency8_Fluency8TTSGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hmi_tts_fluency8_Fluency8TTSGenerator
 * Method:    FluencySpeak
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_fluency8_Fluency8TTSGenerator_FluencySpeak
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hmi_tts_fluency8_Fluency8TTSGenerator
 * Method:    FluencyDummySpeak
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_fluency8_Fluency8TTSGenerator_FluencyDummySpeak
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hmi_tts_fluency8_Fluency8TTSGenerator
 * Method:    FluencyInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_fluency8_Fluency8TTSGenerator_FluencyInit
  (JNIEnv *, jobject);

/*
 * Class:     hmi_tts_fluency8_Fluency8TTSGenerator
 * Method:    FluencyCleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_fluency8_Fluency8TTSGenerator_FluencyCleanup
  (JNIEnv *, jobject);

/*
 * Class:     hmi_tts_fluency8_Fluency8TTSGenerator
 * Method:    FluencySetSpeaker
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_fluency8_Fluency8TTSGenerator_FluencySetSpeaker
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hmi_tts_fluency8_Fluency8TTSGenerator
 * Method:    FluencySpeakToFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hmi_tts_fluency8_Fluency8TTSGenerator_FluencySpeakToFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     hmi_tts_fluency8_Fluency8TTSGenerator
 * Method:    FluencyGetVoices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hmi_tts_fluency8_Fluency8TTSGenerator_FluencyGetVoices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
